### ISSUE TITLE
Python exception: No attribute with the name tbilateral exists. Did you mistype a plugin namespace? | Also crash with GRAY input

### ISSUE THREAD

**Issue by Ken1256** [dubhater/vapoursynth-tbilateral#1]
`pp = core.tbilateral.TBilateral(pp, diameter=5, idev=7, planes=None)`

Windows 10 1809
VapourSynth R45

**Comment by dubhater** [comment]
I replaced the v2 binaries. Download it again.

**Comment by Ken1256** [comment]
Thanks
vapoursynth-tbilateral don't support vs.GRAY? Will crash directly.

**Comment by dubhater** [comment]
It should, I just didn't test that.

**Comment by Ken1256** [comment]
GRAY8: crash 
GRAY16: crash
YUV420P8: fine
YUV420P16: fine
YUV444P8: fine
YUV444P16: fine
RGB24: fine
RGB48: fine

**Comment by dubhater** [comment]
Fixed in v3.
