### ISSUE TITLE
16-bit and restype

### ISSUE THREAD

**Issue by TbtBI** [dubhater/vapoursynth-tbilateral#2]
Hi,
It seems that processing in 16-bit with restype different than 0 is broken. restype=3 gives green output, restype=1/2 is hanging (waiting 1-2min without output).
 ```
video = fvsfunc.Depth(video,16)
video = core.tbilateral.TBilateral(video,restype=1)
```

**Comment by dubhater** [comment]
I'm pretty sure restype 1 and 2 are just very, very slow. It takes my laptop about half a minute to generate one 720x480 frame with restype=1.

The problem with restype=3 was that I missed one place where the pixels were clamped to 0..255 in the original version.
